packages:
  - '.'

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  lefthook: true

# if lockfile out of sync
verifyDepsBeforeRun: error

# 7 days in minutes (7 × 24 × 60)
minimumReleaseAge: 10080
minimumReleaseAgeStrict: false
