name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v6
              with:
                  version: 10.33

            - uses: actions/setup-node@v6
              with:
                  node-version: 24.16
                  cache: pnpm

            - run: pnpm install --frozen-lockfile

            - run: pnpm run lint:check
            - run: pnpm run fmt:check
            - run: pnpm run build
            - run: pnpm run test
            - run: pnpm run test:e2e
